-- TRUNCATE TABLES
TRUNCATE TABLE [local_staging].[dbo].[imp_errors];
TRUNCATE TABLE [local_staging].[dbo].[imp_languages];
TRUNCATE TABLE [local_staging].[dbo].[imp_countries];
TRUNCATE TABLE [local_staging].[dbo].[imp_provinces];
TRUNCATE TABLE [local_staging].[dbo].[imp_cities];
TRUNCATE TABLE [local_staging].[dbo].[imp_companies];
TRUNCATE TABLE [local_staging].[dbo].[imp_languages_company_custom];
TRUNCATE TABLE [local_staging].[dbo].[imp_user_types];
TRUNCATE TABLE [local_staging].[dbo].[imp_status_employees];
TRUNCATE TABLE [local_staging].[dbo].[imp_employees_departments];
TRUNCATE TABLE [local_staging].[dbo].[imp_employees_positions];
TRUNCATE TABLE [local_staging].[dbo].[imp_roles];
